### ISSUE TITLE
Minimize doesn't work 

### ISSUE THREAD

**Issue by reborn322** [Laritello/osu-Library#2]
Minimize doesn't work also can you add minimize tray. Thanks :D

**Comment by Laritello** [comment]
And here i am, almost 3 month later :D
I'm planning on releasing new improved version soon(tm) which will include minimize tray.

**Comment by Laritello** [comment]
[Added](https://github.com/Laritello/osu-Library/commit/d89a2d19fb7b31347df433831933fe26e1eb8e08) minimize function as well as tray icon. Took me almost a year, but i did it.
